### ISSUE TITLE
Unavailable periods not taken into account when more than one customer

### ISSUE THREAD

**Issue by humboldtux** [alextselegidis/easyappointments#453] opened 2018-03-30 13:51 UTC
When a service has more than one customer per appointment configured, unavailable periods are not taken into account, and are available in the calendar to pick an appointment.

On a fresh installation of Easy!Appointments v1.3.0

**Comment by humboldtux** [comment] 2018-03-30 14:04
This is just a display bug: if a customer picks a date which should be unavailable in the calendar, he will get an error when confirming the appointment.

**Comment by alextselegidis** [comment] 2018-04-03 14:26
Hi @humboldtux, 

thanks for posting! You are totally right, I just reproduced the error. 

This will be fixed for 1.3.1 so stay tuned for future updates. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment] 2018-04-19 14:53
Hi @humboldtux, can you provide your setup cause I cannot seem to be able to reproduce the error any more. Maybe another change resulted to fixing this problem. 

You can also check the code in the `hotfix` branch. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment] 2018-04-23 13:59
@humboldtux Any chance to get further on this?

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by humboldtux** [comment] 2018-04-24 06:48
I wasn't able to test the `hotfix` branch, i couldn't make the code to run.

I just tried again with v1.3.0, and was able to reproduce the bug:
* start from a fresh install
* Keep the example data (John Doe user, Test service)
* Create a new unavailable period
* Go to the booking page: unavailable period days are greyed
* Go to test service, increase attendants number, Go to the booking page: unavailable period days are available to choose, but you will get an error at the end of the booking process
* Go to test service, lower attendants number to 1,  Go to the booking page: unavailable period days are greyed

Hope that helps

**Comment by alextselegidis** [comment] 2018-04-25 11:51
Hi @humboldtux, thanks for the info. 

Unfortunately I still cannot reproduce this: 

<img width="418" alt="booking" src="https://user-images.githubusercontent.com/4527441/39244047-be568ed6-488f-11e8-8143-ceff51844828.png">
<img width="449" alt="calendar" src="https://user-images.githubusercontent.com/4527441/39244048-be71f734-488f-11e8-8c29-c7b9c3dfd668.png">
<img width="573" alt="service" src="https://user-images.githubusercontent.com/4527441/39244049-be90ce16-488f-11e8-8f63-0ca5298c2e9d.png">

I think that another fix must have fixed the problem. 

We can check this once again with the 1.3.1 beta1 package.

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Closed by alextselegidis** 2018-04-25 11:51 UTC
Labels: bug

**Comment by humboldtux** [comment] 2018-06-27 13:34
I'm sorry but i'm still experiencing this bug in 1.3.1
Do you need anymore info to reproduce it?

**Comment by SimonKnights** [comment] 2019-02-01 14:41
I still have this problem in v1.3.4. I've got around it by creating several blocks (depending on what the 'attendants number' is for the service. So we allow 14 attendants for a service then I create 14 identical blocks). That works, but it is a bit if a fudge, and time consuming to do. I found that I could insert these directly into the ea_appointments table - so that does make it easier - but would much rather have it fixed if possible.

**Comment by thamzayev** [comment] 2023-09-06 07:56
Hi there,
the issue exists in 1.4.3. When there are more than one participants and unavailability period stretches to more than one dates, only the first date of unavailability period is considered when showing availability calendar to customers.

**Comment by alextselegidis** [comment] 2023-10-09 13:56
Hello! 

This is not an issue with 1.5 any more. 

You can try the latest dev package: 

https://github.com/alextselegidis/easyappointments/releases/download/1.5.0-dev.4/easyappointments-1.5.0-dev.4.zip

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
