### ISSUE TITLE
Email notification error

### ISSUE THREAD

**Issue by MAfni** [alextselegidis/easyappointments#119] opened 2016-02-03 08:48 UTC
Email send by phpmailer on EA 1.1.0 
![notification-error](https://cloud.githubusercontent.com/assets/17042166/12777150/dda3cd0a-ca95-11e5-8b53-025dca807b98.gif)

display with html code

Webserver: localhost IIS running on Windows 10
PHP ver 7

**Comment by alextselegidis** [comment] 2016-02-04 07:58
Hi, thanks for reporting :)

I will try to reproduce the error and report back to you.

**Comment by alextselegidis** [comment] 2016-02-07 10:44
If you open the /application/libraries/notifications.php file you will see that I use PHPMailer to send the email and the instance is set to HTML so that the HMTL header is included and email clients display the message correctly. Apparently this is not happening for you.

Can you tell me which email system are you using in your server (sendmail, SMTP, other)?

**Comment by MAfni** [comment] 2016-02-15 03:01
Thank you for the quick respond. Sorry for the late answer due to converting the localhost to web hosting server. I use SMTP in IIS and I have set mailer = 'smtp' in the phpmailer class but the error still exist. 

Now i have upgrade to EA1.1.1 and hosted to http://studio.learningport.my/

The email now work fine without any problem.

But i currently have to disable google calendar due to this error:

401. That’s an error.

Error: invalid_client
Application: Studio Worksheet
You can email the developer of this application at: mohd.afni@gmail.com
no registered origin
Request Details
* 		proxy=oauth2relay378382903
* 		immediate=false
* 		scope=https://www.googleapis.com/auth/calendar
* 		origin=http://studio.learningport.my
* 		response_type=token
* 		redirect_uri=postmessage
* 		state=1205087208|0.838101193
* 		client_id=6819151763-i4g8cdcfgvp774e2ujh2cu0rcba3r6oq.apps.googleusercontent.com
* 		include_granted_scopes=true
That’s all we know.


Probably it's not due to the EA1.1.1 but the setting at my google developer console.

As a Studio Manager this is all new to me, probably it good if there's a guide from others on Google Calendar setup.

**Comment by alextselegidis** [comment] 2016-02-15 20:04
Nice that you got it working :) 

The google calendar issue comes from invalid configuration because you have to explicitly set the client data (JavaScript origins, Authorized redirect URIs ...) Just do a google search and you will find multiple solutions to this problem. 

So I am going to close this issue because it no longer affects you.

**Closed by alextselegidis** 2016-02-15 20:04 UTC
