### ISSUE TITLE
In case of deletion of one appointment, system sends email to secretaries anyway even if they have email notifications disabled.

### ISSUE THREAD

**Issue by AlessioArtini** [alextselegidis/easyappointments#984] opened 2021-01-21 10:57 UTC
I experienced that in case of deletion of one appointment, system sends email to secretaries anyway even if they have email notifications disabled.
For this reason I suggest to make the following correction on file application/libraries/Notifications.php line 207 as follow:
from                  if ( ! $secretary['settings']['notifications'] === '0')
to                       if ( $secretary['settings']['notifications'] === '0')
version 1.4.1

**Comment by alextselegidis** [comment] 2021-02-01 08:27
Hello! 

Thanks for posting. 

That's a duplicate of #966 which is already fixed on develop and will be released with 1.4.2

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Closed by alextselegidis** 2021-02-01 08:27 UTC
