### ISSUE TITLE
Feature request (1.5.0): Ability to sort services

### ISSUE THREAD

**Issue by eerojaaskelainen** [alextselegidis/easyappointments#1328] opened 2022-11-23 08:35 UTC
Greetings!

It would be nice to be able to sort services.

**Comment by alextselegidis** [comment] 2022-11-29 07:41
Hello! 

Thanks for opening this ticket. 

I'll close this as it is a duplicate of #1161

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Closed by alextselegidis** 2022-11-29 07:41 UTC
