### ISSUE TITLE
Unable to delete any customer when French translation is enabled.

### ISSUE THREAD

**Issue by humboldtux** [alextselegidis/easyappointments#326] opened 2017-05-09 07:03 UTC
When i try to delete a customer (/index.php/backend/customers) the delete confirmation pop-up appears, 
i choose 'delete', but nothing happens, the customer is not deleted.

**Comment by humboldtux** [comment] 2017-05-10 11:53
Unfortunately, nothing in the error log of the web server, nothing relevant in the browser network traffic. I didn't get an error pop-up, DEBUG_MODE set to TRUE.

**Comment by alextselegidis** [comment] 2017-05-11 14:03
Have you performed any modifications in the files? 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by humboldtux** [comment] 2017-05-12 06:43
No i didn't touch anything. But i think i figured what's wrong: the *Confirm* button is not shown in the french interface, only the *Cancel* button:
![delete](https://cloud.githubusercontent.com/assets/65201/25986161/b782b5c0-36ee-11e7-9b39-ae3dfa46e976.png)
And by the way, there is something misleading: in french *Cancel* is translated by *Supprimer* in easyappointments, which means *Delete*, where it should be translated by *Annuler*.

**Comment by humboldtux** [comment] 2017-05-12 06:52
PR #329 fixes this problem, only one button was showed because there were labelled the same. With the translation fix, the 2 buttons are showing, and everything is working now.

**Comment by alextselegidis** [comment] 2017-05-12 13:13
The problem is already fixed in develop branch and will be included in the next release (more info in PR #329).

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Closed by alextselegidis** 2017-05-12 13:13 UTC
Labels: bug
