### ISSUE TITLE
Allow the users to define their own status and assign them to appointments.

### ISSUE THREAD

**Issue by rankun203** [alextselegidis/easyappointments#244] opened 2016-11-15 14:58 UTC
The ability to mark an appointment as `checked-in`, `completed`.

**Comment by alextselegidis** [comment] 2016-11-15 21:28
Marked as a an enhancement, thanks :)

**Comment by rankun203** [comment] 2016-11-23 16:12
I suggest the event status to be [`registered`, `checkedin`, `finished`].

**Comment by alextselegidis** [comment] 2016-11-23 17:28
Thanks for posting!

I think a nice idea would be is we could make these statuses dynamic in the settings page. Like a small management list would be great 👍

**Comment by rankun203** [comment] 2016-11-24 00:49
Yeah, a management list would be great. But if we want the admins to define these statuses, we have to make the input (status text) language agnosticism right? Another way is we define several statuses and let the admins decide which ones to use.

**Comment by alextselegidis** [comment] 2016-11-24 07:39
Yeah you are right, I guess this would be extra work for us so maybe it's better to keep you initial solution with the predefined statuses that can easily be translated. In the future we might add the ability to add custom statuses.

**Comment by rankun203** [comment] 2016-11-24 08:28
As for the check-in process, how could we make the process easier? Maybe a button that indicates the next status?

![image](https://cloud.githubusercontent.com/assets/2988555/20591321/e7e058aa-b262-11e6-8550-d92de3b5bf36.png)

And of course, admins will be able to edit the status in Edit Appointment screen.

![image](https://cloud.githubusercontent.com/assets/2988555/20591345/0633c418-b263-11e6-8791-f6b271c49dc4.png)

How do you think?

**Comment by alextselegidis** [comment] 2016-11-24 08:48
I think that the best solution would be to integrate the select box in the event popup, and update the value with an AJAX request. If you find this too much then I would just let the user to modify the event by opening the editing modal. 

The button could work, but I think that it can be frustrating because you cannot set all the possible statuses.

**Comment by rankun203** [comment] 2016-11-24 13:15
Do we need a way to visualize the attendance status? for example (with colorized backgrounds or dots):

![image](https://cloud.githubusercontent.com/assets/2988555/20599786/0a3e786e-b28b-11e6-9494-604e4f7030d4.png)

**Comment by alextselegidis** [comment] 2016-11-24 14:18
Yeah colored events look good! The dots won't be visible if the appointment duration is short so I would skip that. 

Good Job :) 

<small>
<table>
<tr>
<td><img src="https://dl.dropboxusercontent.com/u/27545985/easyappointments/ea-logo-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by rankun203** [comment] 2016-11-24 16:53
I did a pull request that finished most of the job, https://github.com/alextselegidis/easyappointments/pull/252

About the color of events, let's use 

- Blue (bootstrap-btn-primary) for `registered`.
- Green (bootstrap-btn-success) for `checked_in`.
- Grey for `finished`.
- Yellow (bootstrap-btn-warning) for `wont_come`.

Any better idea?

**Comment by rankun203** [comment] 2016-11-25 02:42
BTW, the way I see the `Check In` button in event popup is like a shortcut. If users want to change the status of an appointment, they could just go to the *Editing Appointment* page. Since we know what's next most likely action to that appointment, so we put *Edit*, *Delete* on the event popup, in this case, an additional *Check In* button (depends on the current status of that appointment) has the smallest invasion to the event popup.

**Comment by rankun203** [comment] 2016-11-25 02:48
And for the appointment statuses, colored events card look good, but will we need the colors for other purpose in the future? or just use as a status indicator?

To me, if there is a multi calendar feature coming out (e.g.: login as an admin, each calendar is for one provider), the colors will be useful to distinguish them.

**Comment by rankun203** [comment] 2016-11-25 05:46
Me and my colleague @ikangiec now think the status may not be the best idea to deal with appointment check in problem. Maybe split them to user's action (Yes, No, Maybe) and admin's action (Check In).

The pull request can be closed if you like to.

**Comment by alextselegidis** [comment] 2016-11-25 12:18
Ok first things first, for now we can use colors for showing the current appointment status as there won't be any multi-calendar feature soon. It is quite possible that it will come in the future but then we will probably change the status display by using some icons, tags/labels or maybe plain text.  

For you second question I cannot see why an appointment status won't solve your original problem. It's a really easy way for admins to keep this info without modifying the appointment notes. The customer has also the ability to cancel an appointment.

**Comment by rankun203** [comment] 2016-11-26 02:03
Agree, colors for appointment status is still the best solution for now.

You are right, the status can solve our original problem. The customer can cancel an appointment, the admin can also delete them, so our option `won't come` becomes unnecessary, also for the `registered` status. All appointments that showing in the calendar are registered, so it's unnecessary too, thirdly, the option `completed` is also not so useful.

We wanted to simplify this, after checking with other softwares, we think we only need to store the check in status. I mean, something like this:

<img width="530" alt="ea" src="https://cloud.githubusercontent.com/assets/2988555/20637318/2edb2cbe-b3bf-11e6-93aa-f32a6ea7a2e7.png">

Colored appointments are still useful, but we only need one dedicated color for checked in appointments then.

**Comment by rankun203** [comment] 2016-11-26 10:31
Did another pull request, hope you will like this solution :)

The statuses are still there, just left only registered and checked_in.

**Comment by ikangiec** [comment] 2016-11-26 16:56
@rankun203 Thanks for the work.

**Comment by alextselegidis** [comment] 2016-11-26 19:54
If we only have two statuses then it's true that we only need two colors. I'll some time to elaborate on this but I will post here soon (after reviewing the pull request). In any case though I would like to thank you for your contribution :)

<small>
<table>
<tr>
<td><img src="https://dl.dropboxusercontent.com/u/27545985/easyappointments/ea-logo-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by teryhill** [comment] 2016-12-12 21:01
I did this in another opensource project. I realize that the translations are the issues.

![appt](https://cloud.githubusercontent.com/assets/4655366/21116591/2b8fda1a-c084-11e6-84e5-db9430ed290d.PNG)

**Comment by supersmart-at** [comment] 2022-01-27 14:41
I would also appreciate to set a default behavior after confirming the transition state. 
I think of a pending state: 
- not sending the confirmation appointment on creation, 
- but on entering the state of "approved" (by admin/user) the confirmation get's sent (same routine as on updating an appointment now.

**Comment by alextselegidis** [comment] 2022-01-27 20:17
@supersmart-at Right, there are many things that can be triggered by status changes and they all make sense, based on the workflows of each company/professional. 

Easy!Appointments will always aims to provide the best tooling for any use case.  

For your case, I think that the following steps would work as well: 

* Disable automated customer notifications.
* Get new appointments with booked/pending status (starting with 1.5). 
* Change the status to confirmed or similar whenever you are ready. 
* Use the new send-email button to trigger the customer notification manually. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment] 2022-10-16 19:05
Pushed in develop branch. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Closed by alextselegidis** 2022-10-16 19:05 UTC
Labels: enhancement
