### ISSUE TITLE
Appointment is not available even when it is

### ISSUE THREAD

**Issue by derekpovah** [alextselegidis/easyappointments#871] opened 2020-08-17 15:36 UTC
We're seeing this error even though the time selected has an available slot.

```
The requested appointment is unfortunately not available. Please select a different hour for your appointment.
```

It looks like it's only happening for services that have multiple attendants possible. Where should I start looking to troubleshoot this issue?

**Comment by wvdvegt** [comment] 2020-08-17 16:00
Might be caused by #826 if time zones of providers and customers do not match (careful inspection showed the develop code removed the wrong item from the list of available slots allowing another selection of the slot and gave me the same error).

**Comment by derekpovah** [comment] 2020-08-17 16:35
In my case, all of the correct times have been removed from the selection options on the booking page.

**Comment by wvdvegt** [comment] 2020-08-18 09:47
After updating to the latest commit in develop, I still get #826 when the timezones are not identical (use Azores for provider and Amsterdam for Client) as my fixes where overwritten. The error show matches yours (but for a single client appointment).

What I see is with these timezones is that when I book 14:00 the slot for 16:00 is removed from the list (at the client side). So I will have to re-apply my fix.

**Comment by wvdvegt** [comment] 2020-08-18 09:51
Attached a patch for 0fe96a2 in the develop branch. 

[patch.diff.txt](https://github.com/alextselegidis/easyappointments/files/5089606/patch.diff.txt)

Please note: Multi-client appointments are not tested.

**Comment by wvdvegt** [comment] 2020-08-18 10:10
Small issue with the patch: the mailing now shows the provider TZ (instead of the client's one).

In 'engine\Notifications\Email.php' line 127 should read:

        $appointment_timezone = $timezones[$customer['timezone']];

so it matches the time mentioned above.

**Comment by derekpovah** [comment] 2020-08-28 21:10
It seems like it has something to do with the `Fixed` vs `Flexible` Availabilities Type. When I select `Fixed` my users don't see this error, but when it is set to `Flexible` they do.

**Comment by alextselegidis** [comment] 2020-09-07 07:36
Hello! 

Some time ago I accidentally stepped on a weird case something like this could happen and it had to do with multiple attendants. 

Is this your case? 

The upcoming v1.4.0 will have this fixed by the way 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment] 2020-09-07 10:22
If that's the case then this is solved. 

I will do some testing rounds to see if I can find any other issues. 

For now this is consider closed but feel free to open another ticket if you experience this after you install v1.4.0. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Closed by alextselegidis** 2020-09-07 10:22 UTC
