### ISSUE TITLE
Feature request: Multiple appointments at the same time

### ISSUE THREAD

**Issue by nicovlachakis** [alextselegidis/easyappointments#87] opened 2015-11-13 19:43 UTC
Is it possible to implement an option to setup a maximum amount of appointments at the same time? Sometimes it's possible to accept multiple appointments at the same time. Does this require a lot of modifications in the code?

**Comment by hopeseekr** [comment] 2015-11-16 15:57
You can create the same provider twice... then you could book them twice...

**Comment by nicovlachakis** [comment] 2015-11-16 17:10
Hopeseekr, that's would be the most oubvious solution. But what I'm looking for needs to be invisible for the clients of the customer. 
The situation is like this: The customer has a business with several rooms that can be reserved for a certain amount of time. The client needs to reserve a room and it doesnt matter which room it is. This part should be invisble. So EasyAppointment should check in the background if there is a timeslot available for one of the rooms and show the time when it it available. On the backend for the customer it would be nice if she can see the rooms (resources) in her daily/weekly overview.

**Comment by pinetree** [comment] 2015-11-18 20:30
Yes, I would like to ask this feature too.
The problem is we have groups of users (clients), each group has a limit of users in.
User can book a service by themself = he becomes a member of this group/class. Also the Administrator can appoint this user manually.
Hope you understand.
Maybe you will help me with advice, I will review the code and database for making necesary changes.

**Comment by alextselegidis** [comment] 2015-12-28 15:45
Hello 

I'm afraid that for now you will have to use hopeseekr's solution because this feature is not available yet. Other users have already asked for this so I will close this issue and re-open it whenever it is planned for integration.

Best Regards, 

Alex

**Closed by alextselegidis** 2015-12-28 15:45 UTC
