### ISSUE TITLE
Add break times after each service

### ISSUE THREAD

**Issue by mahmutelmas06** [alextselegidis/easyappointments#1635] opened 2024-12-13 22:03 UTC
I think there should be an option to wait after xxx minutes before the next service start.
For ex. I have 50 min exercise time. But i want 10 minutes break after 50 min exercise. Than other appointment.
I cannot put 60 minutes exercise time beacause clients thinks that it will last 60 min and complain.

**Comment by alextselegidis** [comment] 2024-12-19 17:31
Duplicate of this 
https://github.com/alextselegidis/easyappointments/issues/1224

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Closed by alextselegidis** 2024-12-19 17:31 UTC
