### ISSUE TITLE
Inconsistency when saving `working_plan_exceptions`

### ISSUE THREAD

**Issue by popod** [alextselegidis/easyappointments#1331] opened 2022-12-03 16:15 UTC
`working_plan_exceptions` is a JSON object and is saved as object in the database.

But in some case, when a provider is saved without `working_plan_exceptions` defined, it is saved as en empty array in database ! This is due to PHP which does not differentiate between objects and array (but this is not the case with JSON).

The problem appears at least here:
https://github.com/alextselegidis/easyappointments/blob/44af526a6fc5e898bc1e0132b2af9eb3a9b2c466/application/models/Providers_model.php#L354

Is this a problem ?

A fix used in other places in the code is to do

```php
krsort($value);

// $value = json_encode($value);
$value = json_encode(empty($value) ? new stdClass() : $value);
```

**Comment by alextselegidis** [comment] 2022-12-05 13:51
Hello! 

Thanks for posting this issue. 

It's true that PHP will not know how to decode an empty array properly and your fix is correct. 

The code checks for an empty object before trying to apply a working plan exception, meaning that this should normally not be a problem. 

Could you replicate an issue due to this behavior? 

If so can you provide the reproduction steps? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by popod** [comment] 2022-12-05 13:57
I'm facing an issue with the API.

But you already do this here : https://github.com/alextselegidis/easyappointments/blob/e53683863d920bdd5dad0c5f72771a5c293a1151/application/models/Providers_model.php#L644

.. in `save_working_plan_exception()` and `delete_working_plan_exception()`.

We could add a check in the code each time this value is used, but I think that this is better to fix this when saving to DB and to have coherent values in db (some this this si saved as `{}` and others times as `[]` which is really not consistent).

**Comment by alextselegidis** [comment] 2022-12-12 08:12
Hello! 

Thanks for providing all the info. 

I've merged your PR 🚀  

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Closed by alextselegidis** 2022-12-12 08:12 UTC
