### ISSUE TITLE
Feature Request: Being able to set time required to prepare before an appointment

### ISSUE THREAD

**Issue by hidde-s** [alextselegidis/easyappointments#1380] opened 2023-07-05 16:44 UTC
It would be great to be able to set a time before and after an appointments to prepare/clean between customers.

If anyone has any workarounds to achieve this that would also be helpful.

Thanks!

**Comment by alextselegidis** [comment] 2023-07-10 06:42
Hello!

You are basically referring to the appointment buffer functionality. 

This is a duplicate of #1224

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Closed by alextselegidis** 2023-07-10 06:42 UTC

**Comment by Thomas-git** [comment] 2023-10-29 17:04
it’s the only feature missing for me to switch to easyappointments!
