### ISSUE TITLE
Service description not displayed/blank on Microsoft Edge (Mobile) - 1.4.2

### ISSUE THREAD

**Issue by mrkylegp** [alextselegidis/easyappointments#1106] opened 2021-08-09 12:31 UTC
Since updating to 1.4.2, I appreciate many of the new fixes such as the sliders now working on mobile properly when choosing a time.

However, for some reason, on Microsoft Edge (Mobile version only) the descriptions for services just show up blank. I tested with other mobile browsers and they don't have this issue. I also cleared cache etc. in edge and it made no difference.

See screenshots. 

EDGE (MOBILE) - BLANK DESCRIPTION
![Screenshot_20210809-221834_Edge](https://user-images.githubusercontent.com/52687659/128706274-93fc199c-d569-4295-a731-691f29f8b4ef.jpg)

FIREFOX (MOBILE) - NORMAL
![Screenshot_20210809-221849_Firefox](https://user-images.githubusercontent.com/52687659/128706279-d4535b50-206a-4491-854b-39197ddbddce.jpg)

CHROME (MOBILE) - NORMAL
![Screenshot_20210809-221900_Chrome](https://user-images.githubusercontent.com/52687659/128706283-a20e153e-10fd-477c-9d4d-4afd25533e19.jpg)

**Comment by alextselegidis** [comment] 2021-08-23 09:22
Hello @mrkylegp, 

Thanks for posting this, I will take a look and try to replicate. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment] 2021-10-04 07:36
Hi @mrkylegp, 

I just tried this again and I cannot reproduce the problem. 

It may alslo have been something else that caused this behavior. 

I'll close this ticket for now but feel free to open a new one in case you have found reproduction steps. 

<small>
<table style">
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Closed by alextselegidis** 2021-10-04 07:36 UTC
