### ISSUE TITLE
-Any Provider- bug -UPDATE- Scheduling bug

### ISSUE THREAD

**Issue by jqtank** [alextselegidis/easyappointments#298] opened 2017-03-11 19:53 UTC
Hi, I just installed v1.2

I'd like to also reference Issue #247 
I actually do like keep "-Any Provider-" sometimes, this is just easier for scheduling. So, I hope Alex does not take this feature away in a future release.

But, I do have a bug. With two providers, both the same day and time, one with time slot open and another with time slot taken.
When I go to frontend and schedule an appointment for the same time slot, choosing "-Any Provider-", both providers have this time slot filled in backend. However, this means one of the providers have a double booking since this time slot was already filled for him. I hope this issue is being considered in the next release. 

UPDATE--
Actually, when I go to frontend and choose one of the providers, the provider's filled time slot still shows. When I schedule this slot, the provider now has triple booked conflict for the same time. So, the issue it seems is not only with -Any Provider-.

**Comment by leonwilberforce** [comment] 2017-03-12 22:10
Im also having an issue with the -Any Provider- not having open slots if you change the the next month

**Comment by alextselegidis** [comment] 2017-03-17 07:33
Will have to check this out .... thanks for posting 👍 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by kealist** [comment] 2017-04-22 15:50
I'm going to just continue here because I don't want to add confusion to #247.   I do not care about an option to enable/disable Any Provider.  I do want Any Provider to stop making erroneous appointments either by (1) allowing clients to double book (2 clients at the same time for one provider) or (2) allowing clients to set appointments outside of a providers working hours or (3) not showing available appointments for all providers.  We have had trouble with all three of these issues with our nine providers.   It causes clients to become upset when they show up to a double booked appointment or when they have an appointment with someone not working.  I have been trying to communicate that Any Provider does not function properly.

**Comment by bullmoose20** [comment] 2017-04-22 16:11
In my case, it was easier to add the option to remove the "any provider" as an option in the back office compared to trying and figure out the logic. My last commit touched about 150 files so hopefully it will make it into the next release. For smaller businesses with less providers, having the option to remove the any provider was a good one. But I agree that there is definitely something wrong with the current implementation of the any provider.

**Comment by mhavo** [comment] 2017-06-13 11:49
Im also having an issue with the -Any Provider- not having open slots. It seems that in my case it checks only the first providers slots. If theyy are open - then any provider shows open slots.

I am also having trouble with showing open slots at all when there are many "not available" times. I have to go month forward and back to show available day.

**Comment by alextselegidis** [comment] 2017-06-13 20:11
You can remove the any provider option commenting out the lines 186 - 187 of `/assets/js/frontend_book.js` file as shown in the example below: 

``` 
// if ($('#select-provider option').length >= 1) {
//   $('#select-provider').append(new Option('- ' +EALang['any_provider'] + ' -', 'any-provider'));
//}
```

This is just a quick work around till I fix the problem. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by mhavo** [comment] 2017-06-14 08:23
Actually what we want to achieve is one product with many providers BUT client doesn't have a possibility to choose the provider. So I made those elements hidden in the form AND made the "-any provider-" as "selected".  Now there won't be open slots if the first provider does have "unavailable" status for the day.

That's also why we need an option just to "open slots" when there are anybody to provide the service. (the other enhancement idea in the list of ideas.)

**Comment by alextselegidis** [comment] 2018-04-26 12:15
Version 1.3.1 has a fix on this issue, can you please take a look and check if the problem is fixed? 

https://github.com/alextselegidis/easyappointments/releases

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment] 2019-01-15 21:04
@avishome Did you still have this issue with v1.3.2? Would be great to know if the issue still persists. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by avishome** [comment] 2019-01-16 08:02
Now I see my solution does not relate to this bug. When the user selects any provider he gets a schedule for each day and only the provider with the most available time. My code show all the free time of all providers

**Comment by alextselegidis** [comment] 2019-01-16 09:12
Hmm, actually I think your approach is slightly better than the current one cause customers who do not wish to select a provider, they should be also granted the option to select any possible booking time. I think it's better to go this way. 

I'd like to know your opinion as well :)

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment] 2020-04-08 08:54
I checked again this problem and it does not seem to affect the latest state (possibly fixed by an other fix) so I will close this ticket. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Closed by alextselegidis** 2020-04-08 08:54 UTC
Labels: bug
