### ISSUE TITLE
Captcha error after put correct letters in Beta Version.

### ISSUE THREAD

**Issue by Presidents** [alextselegidis/easyappointments#95] opened 2015-12-31 12:26 UTC
![captcha](https://cloud.githubusercontent.com/assets/6377812/12064367/acf408a8-afa8-11e5-8086-a5ffd8d6e11e.png)

I put the correct caracters, show this..

I try others 3 times...some message.

ok

thank you for beta version, now with captcha database verify.

**Comment by alextselegidis** [comment] 2015-12-31 14:57
Confirmed! This problem does not happen all the time. 

I could only reproduce it after I had successfully booked an appointment and tried to register a new one. 

If press the "change CAPTCHA" button on the second time it works just fine. 

I will further investigate the issue. Thanks for noticing :)

**Comment by Presidents** [comment] 2015-12-31 15:20
ok, my friend...i made a new folder in cpanel put all scr in...intalled all ok...running captcha show images ok....but show this issue..ok

thanks

**Comment by alextselegidis** [comment] 2016-01-01 19:16
After carefully testing the code again I realised that there is no error in the captcha code. It just happened for me to type wrong captcha phrases for a couple of times. 

As a temporary solution I've added the expected captcha phrase to the error message.

As I cannot really reproduce this problem I will just close the issues until there are some steps to reproduce.

**Closed by alextselegidis** 2016-01-01 19:16 UTC
Labels: bug

**Comment by Presidents** [comment] 2016-01-01 19:58
ok, thanks, let me try.

**Comment by Presidents** [comment] 2016-01-01 20:21
Finally i receiver the email with the appointments. Congrats Alex you solve the main problem...let star the new year with a appointment.

**Comment by Presidents** [comment] 2016-01-01 20:22
Only one more...why my email go to spam folder in gmail?

**Comment by alextselegidis** [comment] 2016-01-01 20:37
I cannot tell. It maybe has to do with the company email address because it doesn't happen with my installation.

**Comment by Presidents** [comment] 2016-01-02 14:13
Ok, i am using google gmail, maybe will be about the script  server dont have informations about smtp account in the script to send the email, like password and login of sender.

**Comment by Presidents** [comment] 2016-01-02 14:16
i am using in other system the require("phpmailer/class.phpmailer.php"); with all credentials to send the email, and works fine.

**Comment by Presidents** [comment] 2016-01-02 14:18
I sent one email to you yesterday...ok. tks
