### ISSUE TITLE
Display issue with iframe (booking wizard).

### ISSUE THREAD

**Issue by juur** [alextselegidis/easyappointments#153] opened 2016-05-10 18:12 UTC
I found that the form entry inside an iframe 'leaked' out of the div tag, due to it being too tall -- this might be a HiDPI issue. The below made the form resize correctly due to the large number of form elements.

```
--- assets/css/frontend.css.orig        2016-05-10 18:34:45.000000000 +0100
+++ assets/css/frontend.css     2016-05-10 18:36:53.000000000 +0100
@@ -69,11 +69,9 @@

 #book-appointment-wizard .wizard-frame {
     padding: 10px 20px;
-    height: 530px;
 }

 #book-appointment-wizard .wizard-frame .frame-container {
-    height: 440px;
     margin-bottom: 10px;
 }
```

**Comment by bbruman** [comment] 2016-05-10 18:48
Changing to `height:auto;` fixed it for me

**Comment by alextselegidis** [comment] 2016-05-31 19:37
Could you possibly provide a screenshot because I cannot reproduce.

**Comment by juur** [comment] 2016-05-31 20:00
Note how the selection box bleeds over the text, with the height tags:

![image](https://cloud.githubusercontent.com/assets/2140626/15688543/7750a106-2772-11e6-8b93-59ca52dbd51a.png)

Then if I remove the height tags:

![image](https://cloud.githubusercontent.com/assets/2140626/15688588/a0e13da0-2772-11e6-9393-c36f267e4d76.png)

**Comment by alextselegidis** [comment] 2016-05-31 20:23
Oh, I understood! This is already registered [here](https://github.com/alextselegidis/easyappointments/issues/137) so I will close this issue. 

Thanks for posting :)

**Closed by alextselegidis** 2016-05-31 20:23 UTC
