### ISSUE TITLE
Bug in Appointments_Model::get_attendants_number_for_period: returns number of attendants for ALL services

### ISSUE THREAD

**Issue by hermannschwaerzlerUIBK** [alextselegidis/easyappointments#892] opened 2020-09-25 09:45 UTC
Hi Everybody,

in `Appointments_Model::get_attendants_number_for_period` a nasty bug is hidden.
This function gets called when a service has an _Attendants Number_ greater than one. It is intended to check how many appointments are already booked for that particular service at a certain time slot.

The code in there creates an SQL query that looks like this:
```
select count(*) as attendants_number 
from ea_appointments 
 where (start_datetime <= '2020-09-25 09:45:00' and end_datetime > '2020-09-25 09:45:00') 
    or (start_datetime < '2020-09-25 10:00:00' and end_datetime >= '2020-09-25 10:00:00') 
   and id_services = 4;
```
If you look closely you will see that the `and id_services =` part (which should limit the result to **one** service) will not have any effect on restricting the results to that particular service as the `or (start_datetime ...)` is on the same level. So the query will return the number of appointments for **all services** at that particular time!
If there is more than one service for the same time period this is a huge problem as the number of attendants of all those services is summed up.

In order to solve this issue another "grouping" level (adding parentheses) is necessary! The change in the code looks like this (adding this makes things work for me):
```
--- a/src/application/models/Appointments_model.php
+++ b/src/application/models/Appointments_model.php
@@ -500,6 +500,7 @@ class Appointments_Model extends CI_Model {
             ->select('count(*) AS attendants_number')
             ->from('ea_appointments')
             ->group_start()
+            ->group_start()
             ->where('start_datetime <=', $slot_start->format('Y-m-d H:i:s'))
             ->where('end_datetime >', $slot_start->format('Y-m-d H:i:s'))
             ->group_end()
@@ -507,6 +508,7 @@ class Appointments_Model extends CI_Model {
             ->where('start_datetime <', $slot_end->format('Y-m-d H:i:s'))
             ->where('end_datetime >=', $slot_end->format('Y-m-d H:i:s'))
             ->group_end()
+            ->group_end()
             ->where('id_services', $service_id)
             ->get()
             ->row()
```

The resulting SQL query looks like this (note the additional parentheses) and gives the correct results:
```
select count(*) as attendants_number 
from ea_appointments 
 where (
       (start_datetime <= '2020-09-25 09:45:00' and end_datetime > '2020-09-25 09:45:00') 
    or (start_datetime < '2020-09-25 10:00:00' and end_datetime >= '2020-09-25 10:00:00') 
 )   
 and id_services = 4;
```
Regards,
Hermann

**Comment by alextselegidis** [comment] 2020-09-25 16:44
Hello! 

Thanks for posting this, however the problem is already fixed on `develop` branch and will be released soon with the v1.4.0 

https://github.com/alextselegidis/easyappointments/blob/develop/application/models/Appointments_model.php#L550

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Closed by alextselegidis** 2020-09-25 16:44 UTC
