### ISSUE TITLE
Problem installing 1.4.2 with composer

### ISSUE THREAD

**Issue by h-e-l-l-o-w-o-r-l-d** [alextselegidis/easyappointments#1109] opened 2021-08-20 14:37 UTC
Hi,

I need to patch EA here and there so I installed it via

`composer require alextselegidis/easyappointments:^1.4`

in a project directory, where EA is stored in the vendor folder. This works. Wondered why it didn't fetch 1.4.2 so I required it explicitely with

`composer require alextselegidis/easyappointments:1.4.2`

and this error occurs: 

  Problem 1
    - Root composer.json requires alextselegidis/easyappointments 1.4.2 -> satisfiable by alextselegidis/easyappointments[1.4.2].
    - alextselegidis/easyappointments 1.4.2 requires codeigniter/framework dev-3.1.11-php8.0 -> found codeigniter/framework[dev-feature/email-attachment-charset, dev-develop, dev-3.1-stable, 3.0rc, ..., 3.1.11] but it does not match the constraint.

composer.json is like this:

{
    "require": {
        "alextselegidis/easyappointments": "^1.4",
        "cweagans/composer-patches": "^1.0"
    },
	"extra":{
		"patches-file": "composer.patches.json",
        "enable-patching": true
    },
    "config": {
        "sort-packages": true
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}

Any hints what might be wrong?

**Comment by alextselegidis** [comment] 2021-08-23 09:10
Hello @h-e-l-l-o-w-o-r-l-d, 

Thanks for posting this, I will take a look and get back to you. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment] 2021-08-24 13:12
I could reproduce the problem is happening while trying to include Easy!Appointments as a composer package into another project.

I'm working on a solution. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment] 2021-08-24 13:24
Alright, I had to re-introduce the system directory into the root directory and remove it from vendor. 

The reason behind this is that the CodeIgniter team hasn't yet released a new version that includes the PHP8 required fixes that are needed for Easy!Appointments to work flawlessly.

In any case this change also made the Easy!Appointments package much smaller, which is a good thing. 

It will be released with 1.5.0, so stay tuned for future updates.

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment] 2021-08-24 13:34
FYI for now you can composer require alextselegidis/easyappointments:dev-develop

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Closed by alextselegidis** 2021-08-24 13:34 UTC
Labels: bug
