### ISSUE TITLE
Booking Screen Calendar Day Mismatch

### ISSUE THREAD

**Issue by Shmnel** [alextselegidis/easyappointments#1560] opened 2024-07-15 02:34 UTC
When on the booking screen from the customer perspective, the calendar disables the button for Friday but allows the button for Sunday to be active, although you cannot select a time. The working schedule is set up from 9:00AM to 6:00PM every weekday. I am running the latest version, 1.5.0

Calendar issue displayed below:
![image](https://github.com/user-attachments/assets/ef109251-f341-48c9-bdda-c2601312ef76)

When using inspect element and removing disable from the class I can select it and schedule a time still.
![image](https://github.com/user-attachments/assets/42991f8f-2ea2-4262-a556-1433ff25ad33)

**Comment by alextselegidis** [comment] 2024-07-15 09:42
Hello! 

Thanks for posting this issue. 

Can you please make sure the provider is also set to Chicago time zone? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by Shmnel** [comment] 2024-07-15 20:29
Yes, both the provider and admin are set to the same time zone and I have reapplied the working plan to all users as well. From the backend it looks correct, but from the customer's end it doesn't let them click Friday, and when disabling Friday from the working plan it disables Thursday on the calendar for the customer.

**Comment by alextselegidis** [comment] 2024-07-22 08:20
Hello! 

Can you please pm me access to the instance so that I can troubleshoot this? 

Email: info@easyappointments.org

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by Shmnel** [comment] 2024-07-23 01:44
I emailed you with the subject of the github issue

**Comment by alextselegidis** [comment] 2024-07-26 11:51
Thanks, I will take a closer look into this and report back. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by fernandoadao** [comment] 2024-08-03 19:40
I have the same error in my installation, the images of the error.
![image](https://github.com/user-attachments/assets/436d4b2d-d6f9-4deb-bdf6-be60d8cc6aa1)
![image](https://github.com/user-attachments/assets/81ef7389-1eb0-46bf-8cc5-e4f41ead82d9)
![image](https://github.com/user-attachments/assets/5bbf1e96-9f66-4713-9e8a-0f2fdb152729)

**Comment by fernandoadao** [comment] 2024-08-03 19:40
![image](https://github.com/user-attachments/assets/ca014d98-ec87-4796-8c5c-f6c6c250dfce)

**Comment by alextselegidis** [comment] 2024-08-05 11:36
Thanks for sharing more info on this. 

It really seems to be an issue with certain timezone configuration. 

Looking into this 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by rfrancis** [comment] 2024-08-07 00:14
Is there any fooling around with timezone etc we can do to help clarify the problem?  (I'm having it too, even with the most barebones new database except for changing the working plan as described above.) We're very psyched here about the application and are very willing to do work to help get past this hurdle.

**Comment by rfrancis** [comment] 2024-08-07 00:15
![image](https://github.com/user-attachments/assets/4005b522-ab7a-4625-9f2e-844b09f70d3f)

As with the others, the working plan is nothing on Saturday and Sunday, which results in this...

**Comment by nickstanko** [comment] 2024-08-21 15:48
Confirming the same issue with the New York timezone.

**Comment by alextselegidis** [comment] 2024-08-26 08:09
Thanks for sharing all this info, this is still on our working list. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by raylopezhdez** [comment] 2024-10-15 07:49
This is unexpected behavior
The apparent solution is to allow the user's PC to sync and get the time zone and time from a time server on the Internet. Many users are behind a proxy without this feature. I hope this comment helps.

**Comment by jlteel** [comment] 2024-10-25 03:09
Is there still no fix for this? Basically, the app is useless for us with this problem then, right? We have a scheduling app that won't let us schedule on the dates we have configured.

**Comment by JaxSulav** [comment] 2024-11-04 00:34
Guys FIY: Someone fixed it here: https://github.com/alextselegidis/easyappointments/pull/1614/commits/528bda041f3023b7c03fcce31db01e4107f8b742

**Comment by alextselegidis** [comment] 2024-11-05 12:22
This is merged and will be released with 1.5.1

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Closed by alextselegidis** 2024-11-05 12:22 UTC
