### ISSUE TITLE
Booking form fields setup

### ISSUE THREAD

**Issue by aiwo79** [alextselegidis/easyappointments#1140] opened 2021-10-04 06:26 UTC
It would be nice to have a possibility to turn off booking form fields like Address, City and Zip Code in the administration.

**Comment by alextselegidis** [comment] 2021-10-04 07:18
Hello! 

Yes, this looks like a good thing to do. 

There's already a PR for this here: 

https://github.com/alextselegidis/easyappointments/pull/1082

I'll review and merge for v1.5
<small>
<table style">
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment] 2021-10-04 07:23
Closing this as duplicate of https://github.com/alextselegidis/easyappointments/issues/1081

<small>
<table style">
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Closed by alextselegidis** 2021-10-04 07:23 UTC
Labels: enhancement
