### ISSUE TITLE
Missing month and year in calendar when adding blocked periods

### ISSUE THREAD

**Issue by tm8544** [alextselegidis/easyappointments#1494] opened 2024-04-12 05:51 UTC
When adding blocked periods, when you go to starting time field, the calendar shows no month name nor year, although it selects correct day. In the attached image the date is  12.4.2024, so the day 12 is selected, but neither month April nor year 2024 is not selected on dropdown.

If I click on day, then month and year are selected.

![image](https://github.com/alextselegidis/easyappointments/assets/15167679/883c4db8-438f-4d6c-a6ac-ed90f6292cdb)

**Comment by alextselegidis** [comment] 2024-04-15 12:10
Hello! 

Thanks for reporting this. 

The issue is fixed on develop by setting default values for new records, otherwise flatpickr will behave oddly on this. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Closed by alextselegidis** 2024-04-15 12:10 UTC
