### ISSUE TITLE
Feature request: Customer Login Link

### ISSUE THREAD

**Issue by Grekkor** [alextselegidis/easyappointments#1454] opened 2024-02-08 11:01 UTC
Here is another feature request which in my opinion is missing.

Repeated customers should be able to book appointments faster by giving them a permanent link they can use.
Or they could type in their email and get sent a new login link every time. This avoids needing a username and password.

Thanks.

**Comment by alextselegidis** [comment] 2024-02-12 09:54
Hello! 

Thanks for the suggestion. 

This is a duplicate of: 

https://github.com/alextselegidis/easyappointments/issues/163

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Closed by alextselegidis** 2024-02-12 09:54 UTC

**Comment by shoei101** [comment] 2024-09-11 18:55
In the reservation e-mail have a unique link that the customer can make modifications/cancel their reservations. No customer portal or customer account creation needed.
