### ISSUE TITLE
Provider page appointment table problem

### ISSUE THREAD

**Issue by arbenek** [alextselegidis/easyappointments#381] opened 2017-12-11 07:34 UTC
Hi, thank you very much for this project. I installed the application to my server, but I have a problem:
More than one service provider is registered in the application. Whichever service provider login the application, only the earliest recorded provider's appointment table appears. However, the provider must see his own appointment table after logging in. Can you help us fix this problem?

![deepinscreenshot_select-area_20171211103212](https://user-images.githubusercontent.com/694928/33820136-e3e8fdc8-de5e-11e7-85c2-363699cf0b06.png)

**Comment by alextselegidis** [comment] 2018-01-12 08:22
Do all providers have a service in the system? 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by arbenek** [comment] 2018-01-12 11:59
Yes. All providers have a service. Same service..

**Comment by arbenek** [comment] 2018-01-29 05:28
Can you find a solution for the problem?

**Comment by alextselegidis** [comment] 2018-01-29 08:13
@arbenek I will check this out later today and report back. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by arbenek** [comment] 2018-02-08 09:42
I deleted old(1.2) version all files and database from my server. I installed new beta version(1.3.0.beta2) and I created new database but same error at provider page appointment table.

Unbelievable!..

**Comment by alextselegidis** [comment] 2018-02-08 21:02
Hi @arbenek, thanks for the reminder. 

The issue is now fixed and will be included in the stable v1.3.0 release. 

You can directly patch your installation as demonstraing in the following commit: 7d6f87f

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Closed by alextselegidis** 2018-02-08 21:02 UTC
Labels: help wanted

**Comment by arbenek** [comment] 2018-02-24 10:09
Thanks a lot! :)
