### ISSUE TITLE
Timezone issue with Safari and iOS devices?

### ISSUE THREAD

**Issue by Elaktrato** [alextselegidis/easyappointments#1455] opened 2024-02-09 14:26 UTC
Version: v1.5.0-dev.4

Currently we are running into an Issue regarding iOS devices and Safari.
Whenever you try to book an appointment on Safari or an iPhone, as soon as you get to the date picker, you get an error as shown in the screenshot below:
<img width="498" alt="image" src="https://github.com/alextselegidis/easyappointments/assets/84176919/9973fa40-24da-4c23-b6de-40fa0f6bad2b">

To be a bit more precise, the affected browsers and devices tested are:
Safari Version 16.0 on MacBook Pro running macOS v12.6
Safari Version 16.6 on iMac running macOS Ventura v13
Google Chrome, Safari and Firefox on an iPhone 12

**Comment by alextselegidis** [comment] 2024-02-12 09:57
Hello! 

Thanks for posting this. I had seen this before so I will make sure it is fixed before 1.5 stable. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by bakx** [comment] 2024-03-19 01:19
I was about to report the same, but see that the original poster could have clarified a few things that help to trace it down.

The issue is related to the 'Time Format' option in general settings. When this is set to 'H:MM AM/PM' , it triggers a warning for all browsers, but on Safari it will also cause a crash on the 3rd step (customer information) and you'll not be able to press the 'Next' button to get to the confirmation screen.

Tested on a Macbook with Safari, iPad Mini as well as an up to date iPhone Max.  Pretty sure it's a Safari thing, it happened on all Apple devices with Safari. 

In the mean time, changing the 'Time Format' to `HH:MM` fixes the issue, but hoping this can be addressed soon

**Comment by alextselegidis** [comment] 2024-03-25 08:25
Hello! 

Thanks for posting this, did you test with 1.4.3 or with 1.5-dev? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment] 2024-03-25 08:57
FYI I checked again the initial issue and could not reproduce with the latest version on Safari. I will close this one but feel free to open in case you find a new case that demonstrates the problem 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Closed by alextselegidis** 2024-03-25 08:57 UTC
Labels: bug
