### ISSUE TITLE
Add global unavailable periord/holiday

### ISSUE THREAD

**Issue by Elvin-Xhimitiku** [alextselegidis/easyappointments#681] opened 2019-12-24 16:49 UTC
Hi

i have this use case: i have over 10 services and providers. Since its from the same company who offers them, when they are on holiday, its holiday for all providers or services.

Now i do: "+ Unavailable" for each provider for the same date/dates. 
Is there a way to do this for all? if not, can you add in a future release?

**Comment by alextselegidis** [comment] 2020-01-09 20:40
Hello @Elvin-Xhimitiku 

closing this as a duplicate of https://github.com/alextselegidis/easyappointments/issues/432

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Closed by alextselegidis** 2020-01-09 20:40 UTC
