### ISSUE TITLE
Feature Request: Option to Set Permanent Timezone in Settings

### ISSUE THREAD

**Issue by sandro-byte32** [alextselegidis/easyappointments#1476] opened 2024-03-14 16:58 UTC
I recently installed your web application and I'm really enjoying its features. However, one aspect that I find could be improved is the requirement to select a timezone during the booking process.

In many cases, especially for personal appointments, the users are likely to be in the same timezone. Therefore, having to select a timezone each time can be a bit cumbersome and not very user-friendly.

I propose adding an option in the settings to set a permanent timezone. This would simplify the booking process and improve the user experience.

I tried to implement this feature myself by uncommenting the timezone dropdown in book.php. However, this caused the available hours to disappear, likely due to the numerous dependencies on the timezone throughout the application.

I believe this feature would be a valuable addition to your application and I hope you will consider implementing it.

**Comment by rabongithub** [comment] 2024-03-15 20:54
v1.43
preset the timezone in 'frontend_book.js' to:
$('#select-timezone').val=('Australia/Brisbane');

After the "$('#select-timezone').val=('Australia/Brisbane');" command add this one "$('#select-timezone').parent().hide();", to hide the component entirely.

**Comment by sandro-byte32** [comment] 2024-03-16 18:22
Thanks alot. Worked!
Maybe thats not a bad idea to add that option to the settings in the Backend.

**Comment by alextselegidis** [comment] 2024-03-18 08:49
Duplicate of https://github.com/alextselegidis/easyappointments/issues/1390

**Closed by alextselegidis** 2024-03-18 08:49 UTC
